### ISSUE TITLE
WASM Support

### ISSUE THREAD

**Issue by backkem** [backkem/go-libp2p-webrtc-direct#20]
Support `js/wasm` build target.

**TODO**
- [x] Support `js/wasm` build target in `pions/datachannel`
- [x] `DataChannel.Detach` support using the `js/wasm` build target in `pions/webrtc`.
- [ ] Test to see if the Dial side works from WASM. (+ Document as example).

**ALTERNATIVE**
We could also build this library using the `OnMessage` callback instead of using `Detach` (when targetting `js/wasm`). However, it seems easier to maintain the wiring around `OnMessage` in pions/datachannel instead.

**Comment by backkem** [comment]
The changes in pions/webrtc#565 make the required changes to support the WebRTC side in WASM.
TODO: Test to see if the Dial side works from WASM. 
The Listen side uses an HTTP server so it won't work unless we move to a different signaling strategy.
